language: python

python:
  - "3.5"

env:
  - TOX_ENV=py35-django-18
  - TOX_ENV=py34-django-18
  - TOX_ENV=py33-django-18
  - TOX_ENV=py27-django-18
  - TOX_ENV=py35-django-19
  - TOX_ENV=py34-django-19
  - TOX_ENV=py27-django-19
  - TOX_ENV=py35-django-110
  - TOX_ENV=py34-django-110
  - TOX_ENV=py27-django-110
  - TOX_ENV=py35-django-111
  - TOX_ENV=py34-django-111
  - TOX_ENV=py27-django-111

matrix:
  fast_finish: true

install: pip install -r requirements.txt tox codecov

script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV
