language: python

python:
  - "3.5"

env:
  - TOX_ENV=py35-django-18
  - TOX_ENV=py34-django-18
  - TOX_ENV=py27-django-18
  - TOX_ENV=py35-django-19
  - TOX_ENV=py34-django-19
  - TOX_ENV=py27-django-19
  - TOX_ENV=py35-django-110
  - TOX_ENV=py34-django-110
  - TOX_ENV=py27-django-110
  - TOX_ENV=py35-django-111
  - TOX_ENV=py34-django-111
  - TOX_ENV=py27-django-111
  - TOX_ENV=py35-django-20

matrix:
  fast_finish: true
  include:
    - python: 3.3
      env: TOX_ENV=py33-django-18
    - python: 3.6
      env: TOX_ENV=py36-django-111
    - python: 3.6
      env: TOX_ENV=py36-django-20

install: pip install -r dev-requirements.txt

script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV
